### PR TITLE
Add a way to make a valid commit in single line

### PR DESCRIPTION
**Pull request by regisrex**
Now, one can use 
```
$ gcm -c <type> -s <scope> -m <commit_message>
```
 to make a valid commit message or use
```
$ gcm 
```
and use the interactive cli to mak a commit

### CODE REVIEW

**Review by veritem — APPROVED** [review]
Bro, urantunguye kbsa. I wrote this back in like two years when I was learning rust. Thank peuh you made my day!!!!

**Comment by veritem** [comment]
I will check sometimes soon and may be make it a cli app people can download.

**Comment by regisrex** [comment]
Yea, I was looking for things to build with rust too and found it interesting 💯 
Find it another name too, gcm is git credential manager :)

**Comment by veritem** [comment]
@regisrex git commit manager 🫠 but you can tell me what you like. I can't think of something right now.

**Pull request merged**
